#! /bin/sh

#A effectuer pour la crontab
# crontab -e
# 0 0 * * * /home/04 

#VAR
path=/etc/crontab

#Ce programme est a executer une fois a vide avant d'etre effectif. Il doit renvoyer 'checknew': No such file or directory au premier lancement.

mv checknew checkold
md5sum $path > ./checknew
CHECKSUM=$(diff checknew checkold)

if [ "x$CHECKSUM" != "x" ]; then
	echo "Automated regards" | mail -s "Le fichier Crontab a ete modifie" root
fi
